### ISSUE TITLE
cannot load pretrained mnist model

### ISSUE THREAD

**Issue by RamyaRaghuraman** [VeriDeep/DLV#6]
Hi all and @matthewwicker @minwu-cs 

I get the following error when I try to run DLV.py:
`Traceback (most recent call last):
  File "C:/Users/RAR7ABT/pj-val-ml/pjval_ml/Verification/DLV/DLV.py", line 447, in <module>
    main()
  File "C:/Users/RAR7ABT/pj-val-ml/pjval_ml/Verification/DLV/DLV.py", line 45, in main
    model = loadData()
  File "basics\loadData.py", line 85, in loadData
    model = NN.read_model_from_file('%s/mnist%s.mat'%(directory_model_string,ae),'%s/mnist%s.json'%(directory_model_string,ae))
  File "networks\mnist_network.py", line 393, in read_model_from_file
    model.layers[lvl].set_weights([weights['weights'][0, weight_1], weights['weights'][0, weight_2].flatten()])
  File "C:\Users\RAR7ABT\AppData\Local\conda\conda\envs\pjval\lib\site-packages\keras\engine\topology.py", line 1200, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (3, 3, 1, 32) not compatible with provided weight shape (32, 1, 3, 3)

Process finished with exit code 1`

Any help would be appreciated. Thank you!

**Comment by RamyaRaghuraman** [comment]
I found the error. just needed to use keras version 1.2.2
